name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Format Check
      run: if [ $(gofmt -l -s . | grep -E -v '^vendor/' | tee /tmp/gofmt.txt | wc -l) -ne 0 ]; then echo "fmt failed:"; cat /tmp/gofmt.txt ; exit 1; fi

    - name: Build linelambda
      run: cd linelambda && go build -v

    #- name: Test
    #  run: go test -v -covermode="count" -coverprofile="/tmp/coverage.out"

    #- name: Coverage Report
    #  run: go tool cover -func="/tmp/coverage.out"

